modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "chiselmon"
version = "${version}"
displayName = "Chiselmon"
authors = "megaturtl"
description = '''
Smooth out your Cobblemon experience!
'''
#logoFile = ""

[[dependencies.chiselmon]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselmon]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselmon]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "chiselmon.mixins.json"
