modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "chiselmon"
version = "${version}"
displayName = "Chiselmon"
authors = "megaturtl"
description = '''
Smooth out your Cobblemon experience!
'''
logoFile="assets/chiselmon/icon.png"

[[dependencies.chiselmon]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselmon]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselmon]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.chiselmon]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselmon]]
modId = "cloth-config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselmon]]
modId = "jade"
type = "optional"
versionRange = "[15.10.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "chiselmon.mixins.json"
